### ISSUE TITLE
Increase Code Coverage (Unit Testing)

### ISSUE THREAD

**Issue by marabesi** [codecasts/codecasts#17]
I think is a good thing to increase the code coverage, isn't it ? 

What do you think guys to open an tread only for this ?

**Comment by hernandev** [comment]
100% on the roadmap, that I will improve here on the issues, coverage is low and very fake right now, since acceptance tests are increasing the coverage by 30% or more.

Priority number one the following weeks, feel free to send some PR's if you want/can.

Thanks
